#!/bin/bash
#┌───────────────────┐
#│ Список переменных │
#└───────────────────┘
NODE_IMAGE='node:22'          # Версия образа
NODE_WORKDIR='/home/node/app' # Рабочий каталог внутри контейнера

#┌───────────────────────────┐
#│ Запускаем новый контейнер │
#└───────────────────────────┘
docker run \
    -w "$NODE_WORKDIR"               \
    -v "$PATH_PROJECT:$NODE_WORKDIR" \
    --rm \
    "$NODE_IMAGE" 'npm' 'i' '--no-package-lock'
